import { Playfair_Display, Manrope, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Navbar";
import Footer from "../components/Footer";
import FooterBottom from "../components/FooterBottom";
import NewSletter from "../components/NewSletter";
import { CartContext } from "../Contexts/CartContext";
import { WishlistContext } from "../Contexts/WishlistContext";
import { Toaster } from "sonner";
import { ProductsContext } from "../Contexts/ProductsContext";
import { AuthContext } from "../Contexts/AuthContext";
import { MenuContext } from "../Contexts/MenuContext";
import { FormContexts } from "../Contexts/FormContexts";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Evara Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${playfair.variable} ${geistMono.variable} antialiased`}
      >

        <AuthContext>
          <MenuContext>
            <ProductsContext>
              <WishlistContext>
                <CartContext>
                  <FormContexts>

                    <Toaster richColors position="top-right" />
                    <NavBar />
                    {children}
                    <NewSletter />
                    <Footer />
                    <FooterBottom />
                  </FormContexts>
                </CartContext>
              </WishlistContext>
            </ProductsContext>
          </MenuContext>
        </AuthContext>
      </body>
    </html>
  );
}
